---
- hosts: all
  tasks:
    - name: Ensure /etc/linux-bsec-exporter exists
      file:
        path: /etc/linux-bsec-exporter
        owner: root
        group: root
        mode: "0755"
        state: directory
    - name: Put linux-bsec-exporter config into place
      copy:
        src: linux-bsec-exporter/config.toml
        dest: /etc/linux-bsec-exporter/config.toml
        owner: root
        group: root
        mode: "0644"
    - name: Put BSEC config into place
      copy:
        src: linux-bsec-exporter/bsec.conf
        dest: /etc/linux-bsec-exporter/bsec.conf
        owner: root
        group: root
        mode: "0644"

- hosts: all
  roles:
    - role: deactivate-power-led
    - role: linux-bsec-exporter
      vars:
        binary_path: /usr/local/bin/linux-bsec-exporter
    - role: rpi-mh-z19c-exporter
      vars:
        binary_path: /usr/local/bin/rpi-mh-z19c-exporter

- hosts: all
  tasks:
    - name: Add Grafana repository key
      apt_key:
        url: https://packages.grafana.com/gpg.key
    - name: Add Grafana repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
    - name: Install Prometheus and Grafana
      apt:
        pkg:
          - prometheus
          - grafana
    - name: Put Prometheus config in place
      copy:
        src: prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        owner: root
        group: root
        mode: "644"
      notify:
        - Reload Prometheus configuration
    - name: Enable Prometheus
      service:
        name: prometheus
        enabled: yes
    - name: Enable Grafana
      service:
        name: grafana-server
        enabled: yes
        state: started
  handlers:
    - name: Reload Prometheus configuration
      service:
        name: prometheus
        state: reloaded
